services:
  web:
    build: .
    container_name: ihealthbrasil-web
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: ihealthbrasil-worker
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ihealthbrasil-redis
    ports:
      - "6379:6379"
