# Generated by Django 5.2.12 on 2026-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_authauditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
