import React, { createContext, useContext, useState, useCallback } from 'react'

const translations = {
  pt: {
    search: 'Pesquisar',
    login: 'Entrar',
    cart: 'Seu carrinho',
    deliver: 'Entregar em:',
    cepTitle: 'Informe seu CEP',
    cepText: 'Vamos calcular a entrega e mostrar a região mais próxima.',
    buscar: 'Buscar',
    usarLocal: 'Usar minha localização atual',
    buscando: 'Buscando...',
    localizando: 'Obtendo localização...',
    cep_invalid: 'Digite um CEP válido com 8 números.',
    cep_not_found_error: 'CEP não encontrado.',
    cep_not_found: 'Não encontrei esse CEP. Verifique e tente novamente.',
    cep_found_success: 'CEP encontrado com sucesso.',
    location_not_supported: 'Seu navegador não suporta localização. Mostrando aproximada.',
    location_approximate: 'Localização aproximada',
    location_updated: 'Localização atual atualizada.',
    location_detected_no_address: 'Localização detectada, mas sem endereço detalhado.',
    location_access_denied: 'Não foi possível acessar sua localização. Mostrando aproximada.',
    filtros: 'Filtros',
    categorias: 'Categorias',
    todos: 'Todos',
    minerais: 'Minerais',
    suplementos: 'Suplementos',
    esporte: 'Esporte',
    saude: 'Saúde',
    cosmeticos: 'Cosméticos',
    sublinguais: 'Sublinguais',
    veterinarios: 'Veterinários',
    bioativos_apicolas: 'Bioativos Apícolas',
    produtosDestaque: 'Produtos em Destaque',
    verTodos: 'Ver todos',
    comprarAgora: 'Comprar agora',
      nav_medicamentos: 'Medicamentos',
      nav_bemestar: 'Bem-Estar',
      nav_naturais: 'Naturais',
      nav_promocoes: 'Promoções',
      banner_outono: 'Promoção de Outono',
      banner_novidades: 'Novidades de Bem-Estar',
      banner_entrega: 'Entrega Rápida',
      login_title: 'Entrar na sua conta',
      login_subtitle: 'Acesse sua conta para continuar suas compras e acessar seus pedidos.',
      email: 'Email',
      email_placeholder: 'seu@email.com',
      password: 'Senha',
      password_placeholder: 'Digite sua senha',
      login_error_required: 'Preencha email e senha.',
      login_error_email: 'Digite um email válido.',
      loading: 'Carregando...',
      entrar: 'Entrar',
      no_account: 'Ainda não tem conta?',
      create_account: 'Criar conta',
      forgot_password: 'Esqueci minha senha',
      or: 'ou',
      login_with_google: 'Entrar com Google',
      register_with_google: 'Criar conta com Google',
      has_account: 'Já tem conta?',
      google_auth_error: 'Não foi possível obter seus dados do Google. Verifique a configuração OAuth.',
      ml_login_title: 'Acesse sua conta na iHealth',
      ml_login_text: 'Encontre produtos, acompanhe pedidos e gerencie suas compras com segurança.',
      ml_benefit_1: 'Entregas rápidas e rastreadas',
      ml_benefit_2: 'Ofertas e descontos exclusivos',
      ml_benefit_3: 'Central de pedidos e suporte',
      register_title: 'Crie sua conta iHealth',
      register_subtitle: 'Cadastre-se para comprar, acompanhar pedidos e receber ofertas.',
      name: 'Nome completo',
      name_placeholder: 'Seu nome completo',
      confirm_password: 'Confirme a senha',
      confirm_password_placeholder: 'Digite novamente sua senha',
      phone: 'Telefone (opcional)',
      phone_placeholder: '(99) 99999-9999',
      terms_text: 'Ao criar sua conta, você concorda com os Termos e a Política de Privacidade.',
      register_error_required: 'Preencha todos os campos obrigatórios.',
      register_error_email: 'Digite um email válido.',
      register_error_password_match: 'As senhas não coincidem.',
  },
  en: {
    search: 'Search',
    login: 'Sign in',
    cart: 'Your cart',
    deliver: 'Deliver to:',
    cepTitle: 'Enter your ZIP code',
    cepText: "We'll calculate shipping and show the nearest area.",
    buscar: 'Search',
    usarLocal: 'Use my current location',
    buscando: 'Searching...',
    localizando: 'Getting location...',
    cep_invalid: 'Enter a valid ZIP code with 8 digits.',
    cep_not_found_error: "ZIP code not found.",
    cep_not_found: "Couldn't find that ZIP. Check and try again.",
    cep_found_success: 'ZIP code found successfully.',
    location_not_supported: "Your browser doesn't support location. Showing approximate.",
    location_approximate: 'Approximate location',
    location_updated: 'Current location updated.',
    location_detected_no_address: 'Location detected but no detailed address.',
    location_access_denied: "Couldn't access your location. Showing approximate.",
    filtros: 'Filters',
    categorias: 'Categories',
    todos: 'All',
    minerais: 'Minerals',
    suplementos: 'Supplements',
    esporte: 'Sports',
    saude: 'Health',
    cosmeticos: 'Cosmetics',
    sublinguais: 'Sublinguals',
    veterinarios: 'Veterinary',
    bioativos_apicolas: 'Bee Bioactives',
    produtosDestaque: 'Featured Products',
    verTodos: 'See all',
    comprarAgora: 'Buy now',
      nav_medicamentos: 'Medicines',
      nav_bemestar: 'Wellness',
      nav_naturais: 'Natural',
      nav_promocoes: 'Promotions',
      banner_outono: 'Autumn Sale',
      banner_novidades: 'Wellness News',
      banner_entrega: 'Fast Delivery',
      login_title: 'Sign in to your account',
      login_subtitle: 'Access your account to continue shopping and view orders.',
      email: 'Email',
      email_placeholder: 'you@email.com',
      password: 'Password',
      password_placeholder: 'Enter your password',
      login_error_required: 'Please provide email and password.',
      login_error_email: 'Enter a valid email address.',
      loading: 'Loading...',
      entrar: 'Sign in',
      no_account: "Don't have an account?",
      create_account: 'Create account',
      forgot_password: 'Forgot password',
      or: 'or',
      login_with_google: 'Sign in with Google',
      register_with_google: 'Sign up with Google',
      has_account: 'Already have an account?',
      google_auth_error: 'Could not fetch your Google profile. Check OAuth setup.',
      ml_login_title: 'Access your iHealth account',
      ml_login_text: 'Find products, track orders and manage your purchases securely.',
      ml_benefit_1: 'Fast, trackable deliveries',
      ml_benefit_2: 'Exclusive offers and discounts',
      ml_benefit_3: 'Order center and support',
      register_title: 'Create your iHealth account',
      register_subtitle: 'Sign up to shop, track orders and receive offers.',
      name: 'Full name',
      name_placeholder: 'Your full name',
      confirm_password: 'Confirm password',
      confirm_password_placeholder: 'Type your password again',
      phone: 'Phone (optional)',
      phone_placeholder: '(99) 99999-9999',
      terms_text: 'By creating an account you agree to the Terms and Privacy Policy.',
      register_error_required: 'Please fill required fields.',
      register_error_email: 'Enter a valid email address.',
      register_error_password_match: "Passwords don't match.",
  },
  es: {
    search: 'Buscar',
    login: 'Iniciar sesión',
    cart: 'Tu carrito',
    deliver: 'Entregar en:',
    cepTitle: 'Ingrese su código postal',
    cepText: 'Calcularemos el envío y mostraremos la zona más cercana.',
    buscar: 'Buscar',
    usarLocal: 'Usar mi ubicación actual',
    buscando: 'Buscando...',
    localizando: 'Obteniendo ubicación...',
    cep_invalid: 'Ingrese un código postal válido con 8 dígitos.',
    cep_not_found_error: 'Código postal no encontrado.',
    cep_not_found: 'No encontré ese código postal. Verifique e inténtelo de nuevo.',
    cep_found_success: 'Código postal encontrado con éxito.',
    location_not_supported: 'Su navegador no admite la ubicación. Mostrando aproximada.',
    location_approximate: 'Ubicación aproximada',
    location_updated: 'Ubicación actual actualizada.',
    location_detected_no_address: 'Ubicación detectada, pero sin dirección detallada.',
    location_access_denied: 'No se pudo acceder a su ubicación. Mostrando aproximada.',
    filtros: 'Filtros',
    categorias: 'Categorías',
    todos: 'Todos',
    minerais: 'Minerales',
    suplementos: 'Suplementos',
    esporte: 'Deporte',
    saude: 'Salud',
    cosmeticos: 'Cosméticos',
    sublinguais: 'Sublinguales',
    veterinarios: 'Veterinarios',
    bioativos_apicolas: 'Bioactivos Apícolas',
    produtosDestaque: 'Productos destacados',
    verTodos: 'Ver todos',
    comprarAgora: 'Comprar ahora',
      nav_medicamentos: 'Medicamentos',
      nav_bemestar: 'Bienestar',
      nav_naturais: 'Naturales',
      nav_promocoes: 'Promociones',
      banner_outono: 'Promoción de Otoño',
      banner_novidades: 'Novedades de Bienestar',
      banner_entrega: 'Entrega Rápida',
      login_title: 'Inicia sesión en tu cuenta',
      login_subtitle: 'Accede para continuar tus compras y ver pedidos.',
      email: 'Correo',
      email_placeholder: 'tu@correo.com',
      password: 'Contraseña',
      password_placeholder: 'Introduce tu contraseña',
      login_error_required: 'Por favor completa el correo y la contraseña.',
      login_error_email: 'Introduce un correo válido.',
      loading: 'Cargando...',
      entrar: 'Entrar',
      no_account: '¿Aún no tienes cuenta?',
      create_account: 'Crear cuenta',
      forgot_password: 'Olvidé mi contraseña',
      or: 'o',
      login_with_google: 'Entrar con Google',
      register_with_google: 'Crear cuenta con Google',
      has_account: '¿Ya tienes cuenta?',
      google_auth_error: 'No se pudo obtener tu perfil de Google. Revisa la configuración OAuth.',
      ml_login_title: 'Accede a tu cuenta iHealth',
      ml_login_text: 'Encuentra productos, sigue pedidos y gestiona tus compras de forma segura.',
      ml_benefit_1: 'Entregas rápidas y rastreables',
      ml_benefit_2: 'Ofertas y descuentos exclusivos',
      ml_benefit_3: 'Centro de pedidos y soporte',
      register_title: 'Crea tu cuenta iHealth',
      register_subtitle: 'Regístrate para comprar, seguir pedidos y recibir ofertas.',
      name: 'Nombre completo',
      name_placeholder: 'Tu nombre completo',
      confirm_password: 'Confirma la contraseña',
      confirm_password_placeholder: 'Escribe de nuevo tu contraseña',
      phone: 'Teléfono (opcional)',
      phone_placeholder: '(99) 99999-9999',
      terms_text: 'Al crear tu cuenta aceptas los Términos y la Política de Privacidad.',
      register_error_required: 'Completa los campos obligatorios.',
      register_error_email: 'Introduce un correo válido.',
      register_error_password_match: 'Las contraseñas no coinciden.',
  },
  fr: {
    search: 'Rechercher',
    login: 'Se connecter',
    cart: 'Votre panier',
    deliver: 'Livrer à :',
    cepTitle: 'Entrez votre code postal',
    cepText: "Nous calculerons la livraison et afficherons la zone la plus proche.",
    buscar: 'Rechercher',
    usarLocal: 'Utiliser ma position actuelle',
    buscando: 'Recherche...',
    localizando: 'Récupération de la position...',
    cep_invalid: 'Entrez un code postal valide à 8 chiffres.',
    cep_not_found_error: 'Code postal introuvable.',
    cep_not_found: "Impossible de trouver ce code postal. Vérifiez et réessayez.",
    cep_found_success: 'Code postal trouvé avec succès.',
    location_not_supported: "Votre navigateur ne prend pas en charge la localisation. Affichage approximatif.",
    location_approximate: 'Emplacement approximatif',
    location_updated: 'Emplacement actuel mis à jour.',
    location_detected_no_address: "Emplacement détecté, mais sans adresse détaillée.",
    location_access_denied: "Impossible d'accéder à votre position. Affichage approximatif.",
    filtros: 'Filtres',
    categorias: 'Catégories',
    todos: 'Tous',
    minerais: 'Minéraux',
    suplementos: 'Suppléments',
    esporte: 'Sport',
    saude: 'Santé',
    cosmeticos: 'Cosmétiques',
    sublinguais: 'Sublinguaux',
    veterinarios: 'Vétérinaire',
    bioativos_apicolas: 'Bioactifs Apicoles',
    produtosDestaque: 'Produits en vedette',
    verTodos: 'Voir tout',
    comprarAgora: "Acheter maintenant",
      nav_medicamentos: 'Médicaments',
      nav_bemestar: 'Bien-être',
      nav_naturais: 'Naturels',
      nav_promocoes: 'Promotions',
      banner_outono: 'Promotion d\'automne',
      banner_novidades: 'Nouveautés Bien-être',
      banner_entrega: 'Livraison rapide',
      login_title: 'Connectez-vous à votre compte',
      login_subtitle: "Accédez à votre compte pour continuer vos achats et voir vos commandes.",
      email: 'Email',
      email_placeholder: 'vous@exemple.com',
      password: 'Mot de passe',
      password_placeholder: 'Entrez votre mot de passe',
      login_error_required: 'Remplissez email et mot de passe.',
      login_error_email: 'Entrez une adresse email valide.',
      loading: 'Chargement...',
      entrar: 'Entrer',
      no_account: "Vous n'avez pas de compte ?",
      create_account: 'Créer un compte',
      forgot_password: 'Mot de passe oublié',
      or: 'ou',
      login_with_google: 'Se connecter avec Google',
      register_with_google: 'Créer un compte avec Google',
      has_account: 'Vous avez déjà un compte ?',
      google_auth_error: 'Impossible de récupérer votre profil Google. Vérifiez la configuration OAuth.',
      ml_login_title: 'Accédez à votre compte iHealth',
      ml_login_text: 'Trouvez des produits, suivez les commandes et gérez vos achats en toute sécurité.',
      ml_benefit_1: 'Livraisons rapides et suivies',
      ml_benefit_2: 'Offres et remises exclusives',
      ml_benefit_3: 'Centre de commandes et support',
      register_title: 'Créez votre compte iHealth',
      register_subtitle: "Inscrivez-vous pour acheter, suivre les commandes et recevoir des offres.",
      name: 'Nom complet',
      name_placeholder: 'Votre nom complet',
      confirm_password: 'Confirmez le mot de passe',
      confirm_password_placeholder: "Saisissez à nouveau votre mot de passe",
      phone: 'Téléphone (facultatif)',
      phone_placeholder: '(99) 99999-9999',
      terms_text: 'En créant un compte, vous acceptez les Conditions et la Politique de confidentialité.',
      register_error_required: 'Remplissez les champs requis.',
      register_error_email: 'Entrez une adresse e-mail valide.',
      register_error_password_match: 'Les mots de passe ne correspondent pas.',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('pt')

  const t = useCallback((key) => {
    return (translations[lang] && translations[lang][key]) || translations.pt[key] || key
  }, [lang])

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}

export default LanguageContext
