# Generated by Django 5.0.1 on 2026-03-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["slug"], name="products_ca_slug_da4386_idx")],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("requires_prescription", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=0)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="products", to="products.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Ex: Tamanho, Cor, Concentração", max_length=120)),
                ("value", models.CharField(help_text="Ex: P, M, G ou Azul, Vermelho", max_length=120)),
                ("sku_suffix", models.CharField(max_length=50)),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Adicional ao preço base", max_digits=10
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variations", to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Variação de Produto",
                "verbose_name_plural": "Variações de Produtos",
                "ordering": ["product", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active"], name="products_pr_is_acti_ca4d9a_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariation",
            index=models.Index(fields=["product"], name="products_pr_product_8015f0_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariation",
            index=models.Index(fields=["product", "name"], name="products_pr_product_429e10_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productvariation",
            unique_together={("product", "name", "value")},
        ),
    ]
