# Generated by Django 5.2.12 on 2026-03-28 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDosage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("strength", models.CharField(help_text="Ex: 500mg, 10mg/5mL, 2%", max_length=100)),
                ("unit", models.CharField(help_text="Unidade de medida (mg, mcg, g, %)", max_length=50)),
                (
                    "frequency_recommendation",
                    models.CharField(
                        blank=True, help_text="Freq. recomendada (ex: 2x ao dia)", max_length=200, null=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False, help_text="Dosagem padrão para este produto")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dosagem de Produto",
                "verbose_name_plural": "Dosagens de Produtos",
                "ordering": ["product", "strength"],
            },
        ),
        migrations.CreateModel(
            name="ProductPackageInsert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt_BR", "Português (Brasil)"),
                            ("en_US", "Inglês (USA)"),
                            ("es_ES", "Espanhol (Espanha)"),
                        ],
                        default="pt_BR",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(help_text="Conteúdo da bula em HTML ou texto")),
                ("file_url", models.URLField(blank=True, help_text="URL de arquivo PDF da bula", null=True)),
                (
                    "requires_prescription_note",
                    models.BooleanField(default=False, help_text="Se marca 'Venda sob prescrição'"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bula de Produto",
                "verbose_name_plural": "Bulas de Produtos",
                "ordering": ["product", "language"],
            },
        ),
        migrations.CreateModel(
            name="SalesRestriction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("age_min", "Idade mínima"),
                            ("age_max", "Idade máxima"),
                            ("region", "Por região/estado"),
                            ("professional_required", "Profissional de saúde requerido"),
                            ("license_required", "Licença/registro especial requerido"),
                            ("custom", "Restrição customizada"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(help_text="Descrição da restrição", max_length=255)),
                ("detail", models.TextField(blank=True, help_text="Detalhes técnicos/completos", null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Restrição de Venda",
                "verbose_name_plural": "Restrições de Venda",
                "ordering": ["product", "restriction_type"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="active_ingredient",
            field=models.CharField(blank=True, help_text="Princípio ativo", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="controlled_substance_class",
            field=models.CharField(
                blank=True, help_text="Classificação de substância controlada (ex: C1, C4)", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="max_age_allowed",
            field=models.IntegerField(default=0, help_text="Idade máxima permitida para compra (0 = sem restrição)"),
        ),
        migrations.AddField(
            model_name="product",
            name="min_age_required",
            field=models.IntegerField(default=0, help_text="Idade mínima permitida para compra (0 = sem restrição)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="requires_prescription",
            field=models.BooleanField(default=False, help_text="Exige prescrição médica"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["requires_prescription"], name="products_pr_require_40d3ec_idx"),
        ),
        migrations.AddField(
            model_name="productdosage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="dosages", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="productpackageinsert",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="package_inserts", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="salesrestriction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sales_restrictions", to="products.product"
            ),
        ),
        migrations.AddIndex(
            model_name="productdosage",
            index=models.Index(fields=["product"], name="products_pr_product_9aa22b_idx"),
        ),
        migrations.AddIndex(
            model_name="productdosage",
            index=models.Index(fields=["product", "is_default"], name="products_pr_product_e1d36a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productdosage",
            unique_together={("product", "strength", "unit")},
        ),
        migrations.AddIndex(
            model_name="productpackageinsert",
            index=models.Index(fields=["product"], name="products_pr_product_74f6f9_idx"),
        ),
        migrations.AddIndex(
            model_name="productpackageinsert",
            index=models.Index(fields=["language"], name="products_pr_languag_b88466_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productpackageinsert",
            unique_together={("product", "language")},
        ),
        migrations.AddIndex(
            model_name="salesrestriction",
            index=models.Index(fields=["product"], name="products_sa_product_f4e639_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrestriction",
            index=models.Index(fields=["restriction_type"], name="products_sa_restric_2831da_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrestriction",
            index=models.Index(fields=["product", "is_active"], name="products_sa_product_0da158_idx"),
        ),
    ]
