# Generated by Django 5.2.12 on 2026-04-04 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productdosage_productpackageinsert_salesrestriction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando pagamento"),
                            ("PAID", "Pago"),
                            ("UNDER_MEDICAL_REVIEW", "Em análise médica"),
                            ("APPROVED", "Aprovado"),
                            ("CANCELLED", "Cancelado"),
                            ("FAILED", "Falha no pagamento"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalPrescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "prescription_type",
                    models.CharField(
                        choices=[
                            ("ELECTRONIC", "Eletrônica"),
                            ("PRINTED", "Impressa"),
                            ("DIGITAL_PHOTO", "Foto Digital"),
                        ],
                        default="DIGITAL_PHOTO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando upload"),
                            ("SUBMITTED", "Enviada"),
                            ("VERIFIED", "Verificada"),
                            ("REJECTED", "Rejeitada"),
                            ("EXPIRED", "Expirada"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(help_text="Arquivo da receita médica", upload_to="prescriptions/%Y/%m/%d/")),
                ("file_size", models.BigIntegerField(editable=False, help_text="Tamanho do arquivo em bytes")),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True, editable=False, help_text="SHA-256 do arquivo para integridade", max_length=64
                    ),
                ),
                (
                    "prescriber_name",
                    models.CharField(
                        blank=True, help_text="Nome do médico/profissional que prescreveu", max_length=200, null=True
                    ),
                ),
                ("prescription_date", models.DateField(blank=True, help_text="Data de emissão da receita", null=True)),
                ("validity_days", models.IntegerField(default=30, help_text="Quantos dias a receita é válida")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="Data/hora de expiração automática", null=True
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, help_text="Notas do verificador (admin/staff)", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Receita vinculada a este pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="products.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Médica",
                "verbose_name_plural": "Receitas Médicas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="products.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="products.product"
                    ),
                ),
                (
                    "product_variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.productvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionAccessAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "username_snapshot",
                    models.CharField(
                        blank=True, help_text="Snapshot do username (caso usuário seja deletado)", max_length=150
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Arquivo enviado"),
                            ("DOWNLOADED", "Arquivo baixado"),
                            ("VIEWED", "Visualizado"),
                            ("VERIFIED", "Verificado (admin)"),
                            ("REJECTED", "Rejeitado (admin)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detalhes customizados (acesso via API/Admin, localização, etc)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="products.medicalprescription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria de Acesso a Receita",
                "verbose_name_plural": "Auditorias de Acesso a Receitas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "status"], name="products_or_user_id_f32cef_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "created_at"], name="products_or_status_4e53ae_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "created_at"], name="products_or_user_id_ab51dd_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalprescription",
            index=models.Index(fields=["order", "status"], name="products_me_order_i_10bdda_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalprescription",
            index=models.Index(fields=["status", "expires_at"], name="products_me_status_7e3960_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalprescription",
            index=models.Index(fields=["file_hash"], name="products_me_file_ha_dac442_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="products_or_order_i_7f4974_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["product"], name="products_or_product_8b49c6_idx"),
        ),
        migrations.AddIndex(
            model_name="prescriptionaccessaudit",
            index=models.Index(fields=["prescription", "action", "created_at"], name="products_pr_prescri_09a2bb_idx"),
        ),
        migrations.AddIndex(
            model_name="prescriptionaccessaudit",
            index=models.Index(fields=["user", "action", "created_at"], name="products_pr_user_id_62c5b2_idx"),
        ),
        migrations.AddIndex(
            model_name="prescriptionaccessaudit",
            index=models.Index(fields=["action", "created_at"], name="products_pr_action_0fe8d7_idx"),
        ),
    ]
