# Generated by Django 5.2.12 on 2026-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order_medicalprescription_orderitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalprescription",
            name="file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="SHA-256 do arquivo para integridade",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medicalprescription",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, editable=False, help_text="Tamanho do arquivo em bytes", null=True
            ),
        ),
    ]
