# Generated by Django 5.2.12 on 2026-04-05 19:58

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_medicalprescription_file_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gateway", models.CharField(default="sandbox_gateway", max_length=50)),
                ("gateway_transaction_id", models.CharField(db_index=True, max_length=120, unique=True)),
                (
                    "gateway_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("EXPIRED", "Vencido"),
                            ("FAILED", "Falhou"),
                            ("REFUNDED", "Estornado"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("BOLETO", "Boleto"),
                            ("CREDIT_CARD", "Cartão de crédito"),
                            ("DEBIT_CARD", "Cartão de débito"),
                            ("UNKNOWN", "Desconhecido"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("provider_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("ihealth_commission_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("commission_rate_applied", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("is_split_calculated", models.BooleanField(default=False)),
                ("raw_last_payload", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transação de Pagamento",
                "verbose_name_plural": "Transações de Pagamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(db_index=True, max_length=120, unique=True)),
                ("event_name", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evento de Webhook de Pagamento",
                "verbose_name_plural": "Eventos de Webhook de Pagamento",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("12.00"),
                help_text="Percentual de comissão da iHealth aplicado no split",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gateway_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Referência do pedido no gateway de pagamento",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Fornecedor parceiro responsável pelo pedido",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["provider", "created_at"], name="products_or_provide_8bc8a1_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["gateway_reference"], name="products_or_gateway_789fd0_idx"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="payment", to="products.order"
            ),
        ),
        migrations.AddField(
            model_name="paymentwebhookevent",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_events",
                to="products.paymenttransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["gateway_status", "last_event_at"], name="products_pa_gateway_4d8675_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["gateway", "gateway_transaction_id"], name="products_pa_gateway_e6b8da_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentwebhookevent",
            index=models.Index(fields=["event_name", "processed_at"], name="products_pa_event_n_bfa15d_idx"),
        ),
    ]
