# Generated by Django 5.2.12 on 2026-04-05 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_medicalprescription_file_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe')], db_index=True, max_length=20)),
                ('external_account_id', models.CharField(db_index=True, max_length=120)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Conectada de Pagamento',
                'verbose_name_plural': 'Contas Conectadas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='PaymentCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe')], db_index=True, max_length=20)),
                ('external_customer_id', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer de Pagamento',
                'verbose_name_plural': 'Customers de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe')], db_index=True, max_length=20)),
                ('gateway_payment_intent_id', models.CharField(db_index=True, max_length=120)),
                ('gateway_checkout_session_id', models.CharField(blank=True, max_length=120)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='brl', max_length=3)),
                ('status', models.CharField(db_index=True, default='requires_payment_method', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='products.paymentconnectedaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='products.paymentcustomer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='products.order')),
            ],
            options={
                'verbose_name': 'Intenção de Pagamento',
                'verbose_name_plural': 'Intenções de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentconnectedaccount',
            index=models.Index(fields=['gateway', 'external_account_id'], name='products_pa_gateway_16a6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentconnectedaccount',
            index=models.Index(fields=['user', 'gateway'], name='products_pa_user_id_0bee59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentconnectedaccount',
            unique_together={('user', 'gateway')},
        ),
        migrations.AddIndex(
            model_name='paymentcustomer',
            index=models.Index(fields=['gateway', 'external_customer_id'], name='products_pa_gateway_36457e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcustomer',
            index=models.Index(fields=['user', 'gateway'], name='products_pa_user_id_45d86d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentcustomer',
            unique_together={('user', 'gateway')},
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['order', 'created_at'], name='products_pa_order_i_9b6171_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'created_at'], name='products_pa_status_6013fd_idx'),
        ),
    ]
