# Generated by Django 5.2.12 on 2026-04-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_paymentconnectedaccount_paymentcustomer_and_more"),
        ("products", "0005_paymenttransaction_paymentwebhookevent_and_more"),
    ]

    operations = []
