# Generated by Django 5.2.12 on 2026-04-05 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_merge_20260405_1707"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("SMS", "SMS")], db_index=True, default="SMS", max_length=20)),
                ("provider", models.CharField(db_index=True, default="mock", max_length=50)),
                ("event_name", models.CharField(db_index=True, max_length=80)),
                ("destination_masked", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Falhou"),
                            ("SKIPPED", "Ignorado"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("external_message_id", models.CharField(blank=True, max_length=120)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("request_metadata", models.JSONField(blank=True, default=dict)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_notifications",
                        to="products.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificacao Externa",
                "verbose_name_plural": "Notificacoes Externas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order", "channel", "created_at"], name="products_ex_order_i_b390ae_idx"),
                    models.Index(fields=["event_name", "status", "created_at"], name="products_ex_event_n_ec0c86_idx"),
                ],
            },
        ),
    ]
