# Generated by Django 5.2.12 on 2026-04-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_phone_number"),
        ("products", "0007_externalnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Fornecedor dono do produto no marketplace",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provided_products",
                to="accounts.user",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["provider", "is_active"], name="products_pr_provider_584075_idx"),
        ),
    ]
