# Generated by Django 5.2.12 on 2026-04-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_provider"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_provide_3617e0_idx",
            old_name="products_pr_provider_584075_idx",
        ),
    ]
