# Generated by Django 5.2.12 on 2026-04-05 22:15

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_rename_products_pr_provider_584075_idx_products_pr_provide_3617e0_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_code", models.CharField(db_index=True, default="BR", max_length=2)),
                ("currency", models.CharField(db_index=True, default="BRL", max_length=3)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="prices", to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Preco do Produto",
                "verbose_name_plural": "Precos dos Produtos",
                "ordering": ["product", "country_code", "currency"],
                "indexes": [
                    models.Index(fields=["product", "country_code", "currency"], name="products_pr_product_ad2b5b_idx"),
                    models.Index(
                        fields=["country_code", "currency", "is_active"], name="products_pr_country_39d182_idx"
                    ),
                ],
                "unique_together": {("product", "country_code", "currency")},
            },
        ),
    ]
