# Generated by Django 5.2.1 on 2026-04-05 18:30

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_productprice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrinho",
                "verbose_name_plural": "Carrinhos",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user"], name="products_car_user_id_14b744_idx"),
                    models.Index(fields=["updated_at"], name="products_car_updated_8f64a2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="products.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to="products.product"
                    ),
                ),
                (
                    "product_variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.productvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Carrinho",
                "verbose_name_plural": "Itens do Carrinho",
                "ordering": ["cart", "created_at"],
                "indexes": [
                    models.Index(fields=["cart"], name="products_car_cart_id_bf018e_idx"),
                    models.Index(fields=["product"], name="products_car_product_7a4f57_idx"),
                    models.Index(fields=["product_variation"], name="products_car_product_c6b2e7_idx"),
                    models.Index(fields=["cart", "created_at"], name="products_car_cart_id_8ca2b5_idx"),
                ],
            },
        ),
    ]
