# Generated by Django 5.2.12 on 2026-04-05 23:35

import products.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart_and_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='file',
            field=models.FileField(help_text='Arquivo da receita médica', storage=products.storage.PrivatePrescriptionStorage(), upload_to='prescriptions/%Y/%m/%d/'),
        ),
    ]
